ForumGames/Blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForumGames/Computer/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="Computer"

urlpatterns = [
    path("account/create", views.create, name="createComputer"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForumGames/ForumGames/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",views.home,name="Home"),
    path("ForumGames/blog", include("Blog.urls"), name="Blog"),
    path("", include("mUser.urls"), name="mUser"),
    path("", include("Computer.urls"), name="createComputer"),
    path("", include("Post.urls"), name="Posts"),
    path("", include("Videogame.urls"), name="Posts"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForumGames/Videogame/urls.py
from django.urls import path
from . import views
app_name='Videogame'
urlpatterns = [
    path("account/newVideogame", views.addVideogame, name="Libreria"),
]

ForumGames/mUser/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name="mUser"

urlpatterns = [
    #path("account/login", auth_views.LoginView.as_view(template_name="html/account/login/Login.html"), name="Login"),
    path("account/login", views.Login.as_view(), name="Login"),
    path("account/logout", views.logout_req, name="Logout"),
    path("account/register", views.register_req, name="Register"),

]

ForumGames/templates/html/GeneralTemplate.html
<!DOCTYPE html>
<html>
    <head>
        {%load static%}
        <link rel="stylesheet" href="{% static 'css/GeneralStyling/GeneralStyle.css' %}">
        <link rel="stylesheet" href="{% static 'css/GeneralStyling/GeneralDiv.css' %}">
        
        {%block newStyleSheet%}
        {%endblock%}
        {%block title%}
        {%endblock%}
    </head>
    <body>
        <header>
            <div  class="header-addConfigurazione">
                {%block contentHeader%}
                {%endblock%}
            </div>
        </header>
        
        <main>  

            <div class="div-menu">
                <h3> 
                    <a href="{%url "Home"%}" class="a-title">
                        {%block LOGO%}
                        {%endblock%}
                    </a> 
                </h3>
                <div class="div-global">

                   
                    
                    {%block tuaConfigurazione%}
                    {%endblock%}


                    {% block content %}
                    {% endblock %} 
                 
                    <article>
                        <div class="div-log"> 
                            <div id="error">
                                
                                {%if messages %}
                                    {%for message in messages%}
                                        {{message}}
                                    {% endfor %}
                                {%endif%}
                            </div>
                        </div>
                    </article>
                </div>                
            </div>
        </main>


        <div class="div-menu-footbar">
            <div class="div-footbar">
                <footbar>
                    
                        {% block footbar %}
                        {% endblock %}
                        | 
                        <span id="subspaninput"> Forum GAMES </span>
                </footbar>
            </div>
        </div>  
    </body>
</html>

ForumGames/templates/html/HomeTemplate.html
{%extends "html/GeneralTemplate.html"%}



{%block contentHeader%}
    {%if user.is_authenticated%}
        <div class="div-log">
            <a href="{%url 'Computer:createComputer'%}"class="a-footer">
                Aggiungi 
            </a>
            un nuovo computer
        </div>
        <br>
        <div class="div-log">
            <a href="{%url 'Videogame:Libreria'%}"class="a-footer">
                Aggiungi 
            </a>
            un videogioco
        </div>
    {%endif%}
{%endblock%}


{%block content%}
    {%block inserimentoPost%}
    {%endblock%}
    <form name="form" class="log" method="POST" enctype="multipart/form-data">
        {%block bodyBlog%}
        {%endblock%}
    </form>
        
    
{%endblock%}


{%block footbar%}
    {%if user.is_authenticated%}
        <span id="subspaninput">
            <a href="{%url 'mUser:Logout'%}" class="a-footer"> Logout </a>
        </span>
    {%else%}
        <span id="subspaninput"> 
            <a href="{% url 'mUser:Login'%}" class="a-footer">
                Login 
            </a>
        </span>
        |
        <span id="subspaninput"> 
            <a href="{%url 'mUser:Register'%}" class="a-footer"> Register </a>
        </span>
    {%endif%}
{%endblock%}

{%block title%}
    <title>
        Home
    </title>
{%endblock%}

{%block LOGO%}
    <span id="subspaninput"> Forum GAMES </span>
{%endblock%}

{%block tuaConfigurazione%}
{%endblock%}