ForumGames/Blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForumGames/ForumGames/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    re_path(r"^$|^\/$|^home\/$",views.home,name="Home"),
    path("ForumGames/blog", include("Blog.urls"), name="Blog"),
    path("", include("mUser.urls"), name="mUser"),
    path("", include("Computer.urls"), name="createComputer"),
    path("", include("Post.urls"), name="Posts"),
    path("", include("Videogame.urls"), name="Posts"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForumGames/Post/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='Post'

urlpatterns = [
    path("", views.postInsert, name="Insert"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ForumGames/Blog/models.py
from django.db import models

# Create your models here.

ForumGames/Blog/views.py
from django.shortcuts import render

# Create your views here.

ForumGames/ForumGames/views.py
from django.shortcuts import render, redirect
from Computer.models import ComponentsComputer
from Post.forms import WritePost
from Post.models import Post
def home(request):

    photo = elPC = post = None
    if request.user.is_authenticated:
        components= ComponentsComputer.objects.filter(nickname_id=request.user.id).all()

        if not components.exists():
            return redirect("Computer:createComputer")
        else:
            post_formatting = Post.objects.filter(user_id=request.user.id).all()
            elPC = []
            photo = []
            for i in range(len(components)):
                elPC.append("CPU: " + components[i].CPU)
                elPC.append("GPU: " + components[i].GPU)
                elPC.append("RAM: " + components[i].RAM)
                elPC.append("MEM: " + components[i].MEM)
                elPC.append("PSU: " + components[i].PSU)
                elPC.append("MOBO: " + components[i].MOBO)
                elPC.append(components[i].PC_Photo)    
        post = WritePost(request.POST or None)
    ctx={"elenco": elPC, "ph": photo, "form": post}

    return render(request=request, template_name="html/ForumGames/Blog.html", context=ctx)
                 
     

ForumGames/templates/html/ForumGames/Blog.html
{%extends "html/HomeTemplate.html"%}

{%block newStyleSheet%}
{%load static%}
<link rel="stylesheet" href="{% static 'css/ConfigurazioneStyle.css' %}">
{%endblock%}

{%block tuaConfigurazione%}
    {%if user.is_authenticated %}
        <div class="div-contenitoreMenu">

            <div class="div-contenitoreMenuInterno">
                <section>
                            <div class="div-sinistra">
                                
                                <div class="div-configurazioneSinistra">
                                    <div class="div-log">
                                        <h5> Le configurazioni di {{user.username}} </h5>
                                    </div>
                            
                                    <div class="config">
                                        {%for i in elenco%}
                                                
                                    
                                            {% if i.url == None %}
                                                <div class="div-log">
                                                    <span id="subspaninput">{{i}}</span>
                                                </div>
                                            {%else%}
                                                <div class="div-log">
                                                    <img src="{{i.url}}" width="90%" height="80%"/>
                                                </div>
                                            {%endif%}
                                            <div class="div-separete"></div>

                                        {%endfor%} 
                                            
                                        

                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                </section>
            </div>
        </div>
        
    {%endif%}
{%endblock%}

{%block bodyBlog%}
    {%if user.is_authenticated %}
        <article>
                    
            <div class="div-InternalMenu">
                <div class="div-log"> 
                    {%csrf_token%}
                    {{form.as_div}}
                    <div class="div-log">
                        <button class="buttonLog" type="submit"  href="{%url "Post:Insert"%}">
                            <div>Inserisci</div>
                        </button> 
                    </div> 
                </div>
            
            <div class="div-separete"></div>
        </article>
    {%endif%}
{%endblock%}


{%block inserimentoPost%}
{%endblock%}